//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eodeditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BookImporter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookImporter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eodeditor.BookImporter", typeof(BookImporter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbund-ID-Nummer (AC-Nummer).
        /// </summary>
        internal static string acnum {
            get {
                return ResourceManager.GetString("acnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie eine Verbund-ID-Nummer (AC-Nummer) ein:.
        /// </summary>
        internal static string acnum1 {
            get {
                return ResourceManager.GetString("acnum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleph Error.
        /// </summary>
        internal static string alephError {
            get {
                return ResourceManager.GetString("alephError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden keine Metadaten gefunden!.
        /// </summary>
        internal static string alephError1 {
            get {
                return ResourceManager.GetString("alephError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Aleph Metadaten Service steht derzeit nicht zur Verfügung..
        /// </summary>
        internal static string alephHttpError1 {
            get {
                return ResourceManager.GetString("alephHttpError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen Zugriff auf die Metadaten von Aleph..
        /// </summary>
        internal static string alephHttpError2 {
            get {
                return ResourceManager.GetString("alephHttpError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen sie wirklich Metadaten von Aleph importieren? Achtung: alle eingegebenen Metadaten gehen verloren!.
        /// </summary>
        internal static string alephImport {
            get {
                return ResourceManager.GetString("alephImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleph Metadaten Import.
        /// </summary>
        internal static string alephImport1 {
            get {
                return ResourceManager.GetString("alephImport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchdeckel.
        /// </summary>
        internal static string bookStructure1 {
            get {
                return ResourceManager.GetString("bookStructure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchdeckel Ende.
        /// </summary>
        internal static string bookStructure2 {
            get {
                return ResourceManager.GetString("bookStructure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titelseite.
        /// </summary>
        internal static string bookStructure3 {
            get {
                return ResourceManager.GetString("bookStructure3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhaltsverzeichnis.
        /// </summary>
        internal static string bookStructure4 {
            get {
                return ResourceManager.GetString("bookStructure4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einleitung.
        /// </summary>
        internal static string bookStructure5 {
            get {
                return ResourceManager.GetString("bookStructure5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapitel.
        /// </summary>
        internal static string bookStructure6 {
            get {
                return ResourceManager.GetString("bookStructure6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhang.
        /// </summary>
        internal static string bookStructure7 {
            get {
                return ResourceManager.GetString("bookStructure7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern.
        /// </summary>
        internal static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen sie wirklich die Sprache ändern? Achtung: damit die Änderung wirksam wird, muss die Anwendung neu gestartet werden!.
        /// </summary>
        internal static string changeLangText {
            get {
                return ResourceManager.GetString("changeLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad zum images-Verzeichnis auswählen.
        /// </summary>
        internal static string choose1 {
            get {
                return ResourceManager.GetString("choose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählter Klassifikations-Pfad.
        /// </summary>
        internal static string choose2 {
            get {
                return ResourceManager.GetString("choose2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Bilddateien gefunden! Erlaubte Dateiformate: JPEG,TIFF,PNG.
        /// </summary>
        internal static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld.
        /// </summary>
        internal static string error10 {
            get {
                return ResourceManager.GetString("error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist ein Pflichtfeld.
        /// </summary>
        internal static string error11 {
            get {
                return ResourceManager.GetString("error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim erstellen von OCRTEXT XML.
        /// </summary>
        internal static string error12 {
            get {
                return ResourceManager.GetString("error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string error13 {
            get {
                return ResourceManager.GetString("error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wurde nicht gefunden! Stellen Sie sicher, dass für jedes Bild eine valide XML Datei vorhanden ist..
        /// </summary>
        internal static string error14 {
            get {
                return ResourceManager.GetString("error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema Fehler in.
        /// </summary>
        internal static string error15 {
            get {
                return ResourceManager.GetString("error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine PDF Datei des Buches angegeben. Bitte wählen Sie diese im Reiter &quot;Section und Pages&quot; aus..
        /// </summary>
        internal static string error16 {
            get {
                return ResourceManager.GetString("error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Benutzername und/oder Passwort eingegeben! Bitte geben Sie Benutzername und Passwort unter &quot;Upload - starten&quot; an..
        /// </summary>
        internal static string error17 {
            get {
                return ResourceManager.GetString("error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung bei Phaidra fehlgeschlagen. Bitte überprüfen sie Benutzername und Passwort..
        /// </summary>
        internal static string error18 {
            get {
                return ResourceManager.GetString("error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Phaidra Server ist nicht erreichbar. Bitte versuchen sie es später erneut..
        /// </summary>
        internal static string error19 {
            get {
                return ResourceManager.GetString("error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann nicht starten.
        /// </summary>
        internal static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Fehler.
        /// </summary>
        internal static string error20 {
            get {
                return ResourceManager.GetString("error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Lesen des Metadaten - Baums ist ein Fehler aufgetreten.
        /// </summary>
        internal static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Lesen der Klassifikationen ist ein Fehler aufgetreten.
        /// </summary>
        internal static string error4 {
            get {
                return ResourceManager.GetString("error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen von PAGEINFO XML ist ein Fehler aufgetreten.
        /// </summary>
        internal static string error5 {
            get {
                return ResourceManager.GetString("error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen von BOOKSTRUCTURE XML ist ein Fehler aufgetreten.
        /// </summary>
        internal static string error6 {
            get {
                return ResourceManager.GetString("error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen von METADATA XML ist ein Fehler aufgetreten.
        /// </summary>
        internal static string error7 {
            get {
                return ResourceManager.GetString("error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim erstellen von UWMETADATA XML ist ein Fehler aufgetreten: es wurde kein Wert gefunden.
        /// </summary>
        internal static string error8 {
            get {
                return ResourceManager.GetString("error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Klassifikation aus.
        /// </summary>
        internal static string error9 {
            get {
                return ResourceManager.GetString("error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In welches Verzeichnis soll das PDF gespeichert werden?.
        /// </summary>
        internal static string export1 {
            get {
                return ResourceManager.GetString("export1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirklich den Export abbrechen?.
        /// </summary>
        internal static string export2 {
            get {
                return ResourceManager.GetString("export2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export abbrechen.
        /// </summary>
        internal static string export3 {
            get {
                return ResourceManager.GetString("export3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie das Buch wirklich in.
        /// </summary>
        internal static string info1 {
            get {
                return ResourceManager.GetString("info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importieren.
        /// </summary>
        internal static string info2 {
            get {
                return ResourceManager.GetString("info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Bestätigung.
        /// </summary>
        internal static string info3 {
            get {
                return ResourceManager.GetString("info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien.
        /// </summary>
        internal static string info4 {
            get {
                return ResourceManager.GetString("info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle Seite mit PID.
        /// </summary>
        internal static string logging1 {
            get {
                return ResourceManager.GetString("logging1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle Buch mit PID.
        /// </summary>
        internal static string logging10 {
            get {
                return ResourceManager.GetString("logging10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Seiten-Upload.
        /// </summary>
        internal static string logging11 {
            get {
                return ResourceManager.GetString("logging11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch mit PID.
        /// </summary>
        internal static string logging12 {
            get {
                return ResourceManager.GetString("logging12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fertigstellen.
        /// </summary>
        internal static string logging13 {
            get {
                return ResourceManager.GetString("logging13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream BOOKINFO hinzu.
        /// </summary>
        internal static string logging14 {
            get {
                return ResourceManager.GetString("logging14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream OCTETS hinzu - Achtung, dies kann einige Minuten in Anspruch nehmen!.
        /// </summary>
        internal static string logging2 {
            get {
                return ResourceManager.GetString("logging2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream UWMETADATA hinzu.
        /// </summary>
        internal static string logging3 {
            get {
                return ResourceManager.GetString("logging3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream PAGEINFO hinzu.
        /// </summary>
        internal static string logging4 {
            get {
                return ResourceManager.GetString("logging4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream STYLESHEET hinzu.
        /// </summary>
        internal static string logging5 {
            get {
                return ResourceManager.GetString("logging5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream THUMBNAIL hinzu.
        /// </summary>
        internal static string logging6 {
            get {
                return ResourceManager.GetString("logging6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream OCRTEXT hinzu.
        /// </summary>
        internal static string logging7 {
            get {
                return ResourceManager.GetString("logging7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream FULLTEXT hinzu.
        /// </summary>
        internal static string logging8 {
            get {
                return ResourceManager.GetString("logging8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge Datastream RIGHTS hinzu.
        /// </summary>
        internal static string logging9 {
            get {
                return ResourceManager.GetString("logging9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung neu starten.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Anwendung jetzt neu gestartet werden? Achtung: alle Eingaben gehen verloren!.
        /// </summary>
        internal static string restartText {
            get {
                return ResourceManager.GetString("restartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht sperren.
        /// </summary>
        internal static string upload1 {
            get {
                return ResourceManager.GetString("upload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wochen.
        /// </summary>
        internal static string upload2 {
            get {
                return ResourceManager.GetString("upload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Buch mit der PID.
        /// </summary>
        internal static string uploadProgress1 {
            get {
                return ResourceManager.GetString("uploadProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wurde erfolgreich erstellt.
        /// </summary>
        internal static string uploadProgress2 {
            get {
                return ResourceManager.GetString("uploadProgress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Information.
        /// </summary>
        internal static string uploadProgress3 {
            get {
                return ResourceManager.GetString("uploadProgress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string voc1 {
            get {
                return ResourceManager.GetString("voc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string voc2 {
            get {
                return ResourceManager.GetString("voc2", resourceCulture);
            }
        }
    }
}
