/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package it.imtech.configuration;

import it.imtech.globals.Globals;
import it.imtech.utility.Utility;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JSeparator;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author mauro
 */
public class FooterPanel extends javax.swing.JPanel {

    public JButton nextButton;
    public JButton prevButton;
    
    private HashMap componentMap;
    
    /**
     * Creates new form FooterPanel
     */
    public FooterPanel() {
        initComponents();
        
        ResourceBundle bundle = ResourceBundle.getBundle(Globals.RESOURCES, Globals.CURRENT_LOCALE, Globals.loader);
        
        //Creazione Footer
        MigLayout foot = new MigLayout("fillx,insets 10 10 10 10");
        this.setLayout(foot);

        nextButton = new JButton(Utility.getBundleString("next", bundle));
        nextButton.setMinimumSize(new Dimension(120,10));
        nextButton.setName("next_button");
        
        prevButton = new JButton(Utility.getBundleString("annulla", bundle));
        prevButton.setMinimumSize(new Dimension(120,10));
        prevButton.setName("prev_button");
        
        this.add(new JSeparator(), "growx, wrap");
        this.add(prevButton, "split,right");
        this.add(nextButton);
        
        createComponentMap();
        
        //this.setBackground(Color.WHITE);
    }
    
    private void createComponentMap() {
        componentMap = new HashMap<String,Component>();
        Component[] components = this.getComponents();
        for (int i=0; i < components.length; i++) {
                componentMap.put(components[i].getName(), components[i]);
        }
    }
    
    public Component getComponentByName(String name) {
        if (componentMap.containsKey(name)) {
            return (Component) componentMap.get(name);
        }
        else return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
