/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package it.imtech.dialogs;

import it.imtech.globals.Globals;
import it.imtech.utility.Utility;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.UIManager;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author mauro
 */
public class BookCollectionDialog extends javax.swing.JDialog {
    
    private int choice;
    
    public int getChoice(){
        return choice;
    }
    
    /**
     * Creates new form ConfirmDialog
     * @param parent
     * @param modal
     * @param text
     * @param title
     * @param type
     */
    public BookCollectionDialog(java.awt.Frame parent, boolean modal,  String title, String text, String buttoncoll, String buttonbook, String buttonko) {
        super(parent, modal);
        ResourceBundle bundle = ResourceBundle.getBundle(Globals.RESOURCES, Globals.CURRENT_LOCALE, Globals.loader);
        
        initComponents();
        this.setTitle(title);
        
        MigLayout main = new MigLayout();
        MigLayout nord = new MigLayout();
        MigLayout sud = new MigLayout("fillx,insets 5 5 5 5");
        
        //getContentPane().setBackground(Color.white);
        getContentPane().setLayout(main);
        
        Icon ico = UIManager.getIcon("OptionPane.warningIcon");
       
        JLabel picture = new JLabel();
        JLabel sentence = new JLabel(text);
        picture.setIcon(ico);

        JPanel north = new JPanel(nord);
        //north.setBackground(Color.WHITE);
        north.add(picture);
        north.add(sentence, "wrap");
        
        JPanel south = new JPanel(sud);
        //south.setBackground(Color.WHITE);
  
        JButton  collButton = new JButton(buttoncoll);//Utility.getBundleString("annulla", bundle));
        collButton.setMinimumSize(new Dimension(120,10));
        collButton.setName("coll_button");
        
        collButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent event)
            {
                choice = 0;
                setVisible(false);
            }
        });
        
        
        JButton bookButton = new JButton(buttonbook);//Utility.getBundleString("confirm", bundle));
        bookButton.setMinimumSize(new Dimension(120,10));
        bookButton.setName("book_button");
        
        bookButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent event)
            {
                choice = 1;
                setVisible(false);
            }
        });
                
        
        JButton  koButton = new JButton(buttonko);//Utility.getBundleString("annulla", bundle));
        koButton.setMinimumSize(new Dimension(120,10));
        koButton.setName("ko_button");
        
        koButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent event)
            {
                choice = 2;
                setVisible(false);
            }
        });
                
        south.add(new JSeparator(), "growx, wrap");
        south.add(bookButton, "split, right");
        south.add(collButton);
        south.add(koButton);
        
        this.add(north, "wrap, growx");
        this.add(south, "wrap, growx");
        this.pack();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - getSize().width) / 2;
        int y = (dim.height - getSize().height) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmDialog dialog = new ConfirmDialog(new javax.swing.JFrame(), true, "", "","","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
